return {
  {
    y = 0,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 1,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = -1,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = 0,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = 1,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = -1,
    name = "minecraft:deepslate_iron_ore",
    z = 2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 0,
    x = 0,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 0,
    x = 0,
    name = "computercraft:turtle_advanced",
    z = 0,
    tags = {
      "minecraft:block/computercraft:turtle",
      "minecraft:block/minecraft:mineable/pickaxe",
    },
  },
  {
    y = 1,
    x = 0,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = 0,
    name = "minecraft:deepslate_iron_ore",
    z = 2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 1,
    x = 1,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = 1,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = 1,
    name = "minecraft:deepslate_iron_ore",
    z = 2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = 2,
    name = "minecraft:deepslate_iron_ore",
    z = -2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 2,
    x = 2,
    name = "minecraft:deepslate_iron_ore",
    z = 2,
    tags = {
      "minecraft:block/minecraft:mineable/pickaxe",
      "minecraft:block/forge:ores/iron",
      "minecraft:block/minecraft:needs_stone_tool",
      "minecraft:block/minecraft:overworld_carver_replaceables",
      "minecraft:block/forge:ore_rates/singular",
      "minecraft:block/forge:ores_in_ground/deepslate",
      "minecraft:block/forge:ores",
      "minecraft:block/minecraft:iron_ores",
    },
  },
  {
    y = 0,
    x = 1,
    name = "minecraft:dirt",
    z = -3,
    tags = {
    },
  },
}